neams-th-coe/cardinal

- .coverage
> Warn on PRs when coverage on new code is <90%

- doc/content/hpc.md
This PR updates the bashrc and provides example run scripts for Bebop.
> Update Bebop instructions

- src/base/OpenMCCellAverageProblem.C
> Allow subdomain names for OpenMC block mappings. 

- doc/content/start.md
- doc/content/tutorials/index.md
- doc/content/tutorials/other_apps.md
- tutorials/other_apps/cardinal_master.i
- tutorials/other_apps/cardinal_sub.i
- tutorials/other_apps/chickadee_master.i
- tutorials/other_apps/chickadee_sub.i
- tutorials/other_apps/turbPipe.oudf
- tutorials/other_apps/turbPipe.par
- tutorials/other_apps/turbPipe.re2
- tutorials/other_apps/turbPipe.udf
- tutorials/other_apps/turbPipe.usr
Tutorial for coupling Cardinal to arbitrary MOOSE applications.
> Other app tutorial

- src/base/OpenMCCellAverageProblem.C
This changes the order of a minor print during the OpenMC setup so as to not get spliced by another print.
> Move print order to not be interrupted by distrib cell print

- include/base/OpenMCCellAverageProblem.h
- include/base/OpenMCProblem.h
- include/base/OpenMCProblemBase.h
- src/base/OpenMCCellAverageProblem.C
- src/base/OpenMCProblem.C
- src/base/OpenMCProblemBase.C
Base class for OpenMC wrappings to simplify code structure a bit
> Openmc base class

- doc/content/bib/cardinal.bib
- doc/content/tutorials/triso_multiphysics.md
- tutorials/gas_assembly/thm.i
- tutorials/gas_compact_multiphysics/openmc_nek.i
- tutorials/gas_compact_multiphysics/openmc_thm.i
- tutorials/gas_compact_multiphysics/thm.i
Small typo fixes and replacement of deprecated syntax in tutorials.
> Minor changes for tutorials.

- doc/content/start.md
Add helpful hint about clearing environment based on user feedback.
> Add user documentation

- include/base/OpenMCProblemBase.h
- src/base/OpenMCCellAverageProblem.C
- src/base/OpenMCProblemBase.C
- test/tests/neutronics/source/geometry.xml
- test/tests/neutronics/source/make_openmc_model.py
- test/tests/neutronics/source/materials.xml
- test/tests/neutronics/source/openmc.i
- test/tests/neutronics/source/settings.xml
- test/tests/neutronics/source/tests
> Allow initial source to be taken from previous Picard iteration. 

- tutorials/gas_assembly/thm.i
- tutorials/gas_compact_cht/solid_thm.i
- tutorials/gas_compact_cht/thm.i
- tutorials/gas_compact_multiphysics/thm.i
Input files can be a bit simpler by removing this extraneous syntax.
> Don't use max() inside Nu function.

- include/userobjects/LayeredGapBin.h
- include/userobjects/PlaneSpatialBinUserObject.h
This fixes several minor clang warnings.
> Minor clang warning corrections

- doc/content/start.md
Thank you @lewisgross1296 for coordinating with the MOOSE team to figure out how to address this common error!
> Add specific instructions for how to fix TestHarness module find error.

- src/base/NekRSSeparateDomainProblem.C
Quick fixes to NekRSSeparateDomainProblem
> Fix error in dP calculation, initialize coupling_type booleans

- src/base/NekRSProblemBase.C
> Inform NekRS the value of nrs->isOutputStep.

- src/mesh/NekRSMesh.C
- test/tests/nek_file_output/avg_plugin/casedata.h
- test/tests/nek_file_output/avg_plugin/nek.i
- test/tests/nek_file_output/avg_plugin/tests
- test/tests/nek_file_output/avg_plugin/turbPipe.oudf
- test/tests/nek_file_output/avg_plugin/turbPipe.par
- test/tests/nek_file_output/avg_plugin/turbPipe.re2
- test/tests/nek_file_output/avg_plugin/turbPipe.udf
- test/tests/nek_file_output/avg_plugin/turbPipe.usr
This adds a `CheckFiles` test to make sure that `nrs->isOutputStep` has the correct behavior when used within Cardinal.
Closes #371
> Add test for correct isOutputStep behavior

- config/openmc.mk
> Do not make a directory in LIBMESH_DIR for openmc compile

- doc/content/hpc.md
- scripts/job_sawtooth
Update the Sawtooth build instructions.
> Update Sawtooth instructions and add job script

- doc/content/start.md
> Clarify default behavior for OpenMC and NekRS enables. Refs #409

- include/base/NekInterface.h
- include/base/NekRSProblemBase.h
- src/base/NekInterface.C
- src/base/NekRSProblem.C
- src/base/NekRSProblemBase.C
This PR takes some of the content from @anshchaube's branch and adds a general function to do a boundary interpolation, plus defined indices for indexing into the usrwrk array (I left the `NekRSSeparateDomainProblem` alone for now).
> Add boundary interpolation function and usrwrk indices

- scripts/plot_nek_logfile.py
This adds a script to plot the NekRS console output as a function of timestep; this can be useful for making decisions on what time step to use, preconditioners, etc.
> Nek plotting scripts

- scripts/plot_nek_logfile.py
This extends #428 by adding plotting of the max/min solution quantities (velocity, pressure, scalars) as a function of simulation time as one means for quickly assessing whether temporal convergence has been reached.
> Add ability to plot temporal convergence

- doc/content/hpc.md
- scripts/job_summit
This PR adds a Summit job script to the website.
> Summit job script

- doc/content/tutorials/pincell1.md
Some typos, some sentence modifications, and removing $ from copy commands.
> Pincell Tutorial Typos

- doc/content/faq.md
Thank you @milljm for correcting my understanding of switching b/w conda vs. scripts petsc/libmesh!
> Correct understanding about conda vs. script petsc/libmesh

- src/base/OpenMCCellAverageProblem.C
Need to be sure no user encounters this until #457 is addressed.
> Prevent user bug until fix.

- scripts/plot_nek_logfile.py
This PR checks for zero values when computing relative differences of the max/mins in the NekRS field files for plotting.
> Nek plotting script improvements

- doc/content/cross_sections.md
- scripts/download-test-suite-cross-sections.sh
> Change XS instructions.

- src/base/NekRSProblem.C
- src/base/NekRSProblemBase.C
We can move the check on NekRS rank before we first do all the collection of volume node information to reduce unnecessary computations.
> Move rank check outside loop to speed up volume interpolation

- include/base/OpenMCCellAverageProblem.h
- include/base/OpenMCProblemBase.h
- src/base/OpenMCCellAverageProblem.C
- src/base/OpenMCProblemBase.C
- src/postprocessors/TallyRelativeError.C
This refactors the standard deviation tally calculations into the framework of a general mapping of a tally from OpenMC to MOOSE.
> Replace unrelaxed tally std dev with common function.

- .gitmodules
Ping @aprilnovak 
I updated the moose-based submodules while I was here. Let me know if I should yank any of them back.
> Move NCRC submodules to github.inl.gov, update submodules

- Makefile
- config/check_deps.mk
> Use truthy detection for optional dependencies. 

- include/base/OpenMCCellAverageProblem.h
- src/base/OpenMCCellAverageProblem.C
- src/base/OpenMCProblemBase.C
Reduce screen output for debug builds with a few corrections on type.
> Minor warning corrections for debug build

- include/base/OpenMCProblemBase.h
- src/base/OpenMCProblemBase.C
This adds a convenience function for finding if the geometry contains CSG and/or DAG universes.
> Add function to obtain geometry types from OpenMC

- .gitmodules
- config/check_deps.mk
- doc/content/bison_instructions.md
- doc/content/dependencies.md
- scripts/get-bison.sh
- test/tests/bison_coupling/bison_master/bison.i
- test/tests/bison_coupling/bison_master/cardinal_sub.i
- test/tests/bison_coupling/bison_master/tests
- test/tests/bison_coupling/bison_sub/bison_sub.i
- test/tests/bison_coupling/bison_sub/cardinal.i
- test/tests/bison_coupling/bison_sub/tests
To support INL efforts to couple OpenMC with BISON, this adds BISON as a submodule with tests to cover running BISON as either the main or sub app.
> Add BISON as a submodule

- doc/config.yml
> Add google analytics

- include/base/OpenMCCellAverageProblem.h
- include/base/OpenMCProblemBase.h
- src/base/OpenMCCellAverageProblem.C
- src/base/OpenMCProblemBase.C
- test/tests/neutronics/feedback/lattice/non_material_fluid.i
Minor refactoring to support a potential tally system redesign.
> Move 'scaling' and other basic functionality into base class.

- doc/content/source/postprocessors/OpenMCParticles.md
- include/base/OpenMCProblemBase.h
- include/postprocessors/OpenMCParticles.h
- src/base/OpenMCCellAverageProblem.C
- src/postprocessors/OpenMCParticles.C
- test/tests/postprocessors/openmc_particles/geometry.xml
- test/tests/postprocessors/openmc_particles/gold/openmc_out.csv
- test/tests/postprocessors/openmc_particles/materials.xml
- test/tests/postprocessors/openmc_particles/openmc.i
- test/tests/postprocessors/openmc_particles/settings.xml
- test/tests/postprocessors/openmc_particles/tests
> Add postprocessor to extract number of particles simulated.

- doc/content/tutorials/cht2.md
- tutorials/sfr_7pin/duct.i
- tutorials/sfr_7pin/sfr_7pin.par
- tutorials/sfr_7pin/solid.i
- tutorials/sfr_7pin/tests
> Update 7pin tutorial to eliminate bad transfer.

- include/postprocessors/NekSideFieldPostprocessor.h
> Fixing incorrect include

- src/base/OpenMCCellAverageProblem.C
Made this mistake myself - we can give a warning.
> Add warning about heating score.

- src/base/OpenMCCellAverageProblem.C
Running test suite on clang, fixed some minor issues about casting and vector erasing which worked on GNU.
> Clang fixes

- src/base/OpenMCCellAverageProblem.C
> Shorten material name printout for duplicate names.

- doc/content/tutorials/gas_compact.md
- doc/content/tutorials/openmc_fluid.md
- doc/content/tutorials/transfers.md
- test/tests/fluid_prop_subs/iapws95.i
- test/tests/fluid_prop_subs/potassium.i
- test/tests/fluid_prop_subs/sodium.i
- test/tests/neutronics/feedback/lattice/openmc_master.i
- test/tests/neutronics/feedback/single_level/openmc_master.i
- test/tests/neutronics/feedback/unmapped_moose/openmc_master.i
- test/tests/sockeye_coupling/sockeye_master/flow_only_convection.i
- test/tests/sockeye_coupling/sockeye_sub/flow_only_convection.i
- tutorials/gas_assembly/openmc.i
- tutorials/gas_compact/openmc.i
- tutorials/gas_compact_multiphysics/openmc_nek.i
- tutorials/gas_compact_multiphysics/openmc_thm.i
- tutorials/lwr_solid/solid.i
- tutorials/lwr_solid/solid_um.i
- tutorials/pebbles/solid.i
- tutorials/pebbles/solid_um.i
- tutorials/transfers/main.i
> Update transfer names. 

- test/tests/cht/nondimensional/sfr_pin.par
- test/tests/cht/nondimensional/sfr_pin_turb.par
- test/tests/cht/sfr_pincell/sfr_pin.par
Removes an unused input flag (I think).
> Unused variableDT

- include/base/NekInterface.h
- src/base/NekInterface.C
- src/base/NekRSProblem.C
NekRS's mesh solver is not an elasticity solver, so we should correct this language.
> Rename hasElasticitySolver to hasBlendingSolver

- include/base/NekInterface.h
- src/actions/NekInitAction.C
- src/base/NekInterface.C
- src/base/NekRSProblem.C
- src/base/NekRSProblemBase.C
- src/base/NekRSSeparateDomainProblem.C
- src/mesh/NekRSMesh.C
- src/postprocessors/NekSidePostprocessor.C
- src/userobjects/NekBinnedPlaneIntegral.C
- src/userobjects/NekBinnedSideIntegral.C
- src/userobjects/NekBinnedVolumeIntegral.C
- src/userobjects/NekSideSpatialBinUserObject.C
These namespaces aren't really necessary, so we can simplify the syntax a bit.
> Simplify nekrs namespaces

- tutorials/gas_compact/unit_cell.py
> Return entropy mesh flag and capability to unit cell function

- config/check_deps.mk
SAM removed conflicts and allows for compilation with THM now. Removes Cardinal's objection to SAM+THM compilation.
> allow SAM+THM compilation

- doc/content/theory/les_filter.md
- src/base/OpenMCCellAverageProblem.C
> Reinstate the mesh tally volume info

- doc/content/theory/les_filter.md
- doc/content/tutorials/cht4.md
- doc/content/tutorials/cht5.md
- doc/content/tutorials/nek_intro.md
- tutorials/pebble_1/pebble.usr
- tutorials/pebble_1/pebble_cht.par
- tutorials/pebble_1/pebble_cht.usr
- tutorials/pebble_1/solid.i
- tutorials/pebble_67/moose.i
- tutorials/pebble_67/nek.i
- tutorials/pebble_67/pb67.udf
Small modifications to the NekRS tutorials in preparation for the Nureth workshop.
> Minor tutorial modifications

- doc/content/tutorials/openmc_fluid.md
- tutorials/gas_assembly/openmc.i
> Code Snippet Doc Fix

- include/userobjects/NekScalarValue.h
- src/userobjects/NekScalarValue.C
For converting from dimensional to non-dimensional form in NekRS.
> Add scaling parameter to NekScalarValue

- tutorials/gas_assembly/openmc.i
Accidentally missed this duplicate line when updating syntax.
> Remove duplicates

- src/actions/CardinalAction.C
- src/userobjects/NearestPointReceiver.C
We should merge https://github.com/idaholab/civet_recipes/pull/1580 before merging this so that the new container is used on devel.
> Update moose submodule and use common container

- apptainer/README.md
- apptainer/app_environment
- apptainer/app_post_post_install
- apptainer/app_post_pre_make
- apptainer/app_test_begin
- scripts/download-openmc-cross-sections.sh
- test/tests/userobjects/moab_skinner/graveyard/tests
- test/tests/userobjects/moab_skinner/output/tests
- test/tests/userobjects/moab_skinner/second_order/tests
- test/tests/userobjects/moab_skinner/tests
> Add apptainer context for generating an apptainer image of cardinal

- src/base/CardinalApp.C
- src/main.C
- src/postprocessors/NekSidePostprocessor.C
- test/src/base/CardinalTestApp.C
- test/tests/nek_standalone/lowMach/tests
- test/tests/nek_stochastic/device/tests
- test/tests/nek_stochastic/quiet_init/tests
- test/tests/userobjects/moab_skinner/graveyard/tests
- test/tests/userobjects/moab_skinner/output/tests
- test/tests/userobjects/moab_skinner/second_order/tests
- test/tests/userobjects/moab_skinner/tests
- test/tests/userobjects/side/nondimensional/tests
- tutorials/standalone/tests
- unit/src/main.C
Refs [idaholab/moose#25994](https://github.com/idaholab/moose/pull/25994)
> Use new moose main, update moose

- doc/content/hpc.md
- scripts/job_frontier
> Frontier compilation instructions

- include/base/OpenMCCellAverageProblem.h
- scripts/job_sawtooth
- src/base/OpenMCCellAverageProblem.C
FYI @lewisgross1296 actually cmake is needed for Nek. Also, you cannot have hashtags on PBS lines, they are not interpreted as comments.
> Fix Sawtooth script

- include/base/OpenMCCellAverageProblem.h
- include/base/OpenMCProblemBase.h
- src/base/CardinalApp.C
- src/base/OpenMCCellAverageProblem.C
- src/base/OpenMCProblemBase.C
- test/tests/openmc_errors/cell_instances/lattice_outer/geometry.xml
- test/tests/openmc_errors/cell_instances/lattice_outer/materials.xml
- test/tests/openmc_errors/cell_instances/lattice_outer/model.py
- test/tests/openmc_errors/cell_instances/lattice_outer/settings.xml
- test/tests/openmc_errors/cell_instances/lattice_outer/temp.i
- test/tests/openmc_errors/cell_instances/lattice_outer/tests
See https://github.com/openmc-dev/openmc/pull/2996
> add useful error message for lattice.outer

- run_tests
> Use contrib/moose in the test harness

- doc/moosedocs.py
> Use contrib/moose in `moosedocs.py`

- Makefile
- include/base/CardinalApp.h
- scripts/download-openmc-cross-sections.sh
- src/base/CardinalApp.C
Ping @aprilnovak. This is ready.
> Add tutorials to install, allow `curl` for getting cross sections

- src/base/CardinalApp.C
> allow ints for ci mode

- src/actions/NekInitAction.C
> Simplify nekrs command line arguments

- doc/content/hpc.md
- doc/content/without_conda.md
- scripts/get-dependencies.sh
In reference to discussion on #992
> inform users of all env vars for speedup

- doc/content/hpc.md
- scripts/job_improv
> Adding HPC instructions for ANL's Improv 

- include/tallies/MeshTally.h
- src/tallies/CellTally.C
- src/tallies/MeshTally.C
> Rename variables in tally classes.

- src/base/OpenMCCellAverageProblem.C
> Ensure duplicate / invalid entries are removed from mapped_cells

- doc/content/hpc.md
- scripts/job_polaris
The job script successfully runs the pincell multiphysics tutorial case in CPU mode and the instructions build NekRS with CUDA support. I don't have any experience submitting jobs that run on GPUs; feel free to suggest modifications to enable NekRS mixed runs!
Closes #757
> Adding HPC instructions for ANL's Polaris

- doc/content/hpc.md
- scripts/job_bitterroot
> Adding build instructions for bitterroot

- doc/content/hpc.md
- scripts/job_sawtooth
> changed cardinal build instructions (#1048)

- test/tests/neutronics/adaptivity/tests
> Tag adaptivity tests

- include/base/OpenMCCellAverageProblem.h
- src/base/OpenMCCellAverageProblem.C
> Refactor to remove duplicate mapping generation in syncSolutions()

- src/base/OpenMCCellAverageProblem.C
- src/tallies/CellTally.C
> Update OpenMC to remove gsl

- doc/content/hpc.md
- doc/content/hpc_build_tips.md
> Add tips and resources for HPC builds.

- doc/content/publications.md
Didn't know if an issue was necessary for SQA since I'm only updating the publications list. Let me know if I need to add one
> Add the initial AMR paper from ANS 2025

- test/tests/neutronics/photon/tests
This is being performed posthumously for SQA purposes. Closes #1114
> Tag the photon heating test

- doc/content/news/june2025.md
> Add the Embree+Double-Down change to June 2025's news

- scripts/download-openmc-cross-sections.sh
noticed when building on a different machine that we never updated these script colors
> update script colors

- include/base/NekInterface.h
- include/base/NekRSProblem.h
- src/actions/DimensionalizeAction.C
- src/base/NekInterface.C
- src/base/NekRSProblem.C
- src/base/OpenMCCellAverageProblem.C
- src/postprocessors/NekPointValue.C
- src/transfers/NekBoundaryFlux.C
- src/transfers/NekMeshDeformation.C
- src/transfers/NekVolumetricSource.C
In order to support the FFTB data transfer, we will need to generalize the nondimensional system to support non-dimensionalizing additional fields going in to NekRS.
> Generalize nondimensional system

- doc/content/hpc.md
Added python module to bitterroot build instructions.
Closes #1219
> Update Bitterroot build instructions
