include/base/NekInterface.h, include/base/OpenMCCellAverageProblem.h, src/base/NekInterface.C, src/base/OpenMCCellAverageProblem.C
For very large meshes, my cases on Bebop are crashing during the call to `createMesh`, possibly due to memory. We don't technically need to call this function, because we already have all the necessary information, for first order meshes at least.
This PR simply replaces the function call by explicit usage of existing mesh info.
=> Skip mesh duplication for first-order mesh mirrors.

include/base/OpenMCCellAverageProblem.h, include/base/OpenMCProblemBase.h, src/base/OpenMCCellAverageProblem.C, src/base/OpenMCProblemBase.C
This adds a base class for OpenMC wrappings, similar to the Nek case; this clears up a lot of basic functionality from the wrapping.
=> Openmc base class

doc/content/tutorials/cht2.md, doc/content/tutorials/logfile.md, doc/content/tutorials/pincell1.md, doc/content/tutorials/triso.md, include/base/NekRSProblem.h, src/base/NekRSProblem.C, src/base/NekRSProblemBase.C, src/base/OpenMCCellAverageProblem.C, src/mesh/NekRSMesh.C, test/tests/openmc_errors/block_mappings/tests, test/tests/openmc_errors/densities/tests, test/tests/openmc_errors/tallies/tests, test/tests/openmc_errors/xs_temperatures/tests
This updates the OpenMC and Nek wrappings to use the `VariadicTable` in MOOSE to prettify the screen output.
=> Prettify screen output

include/base/NekRSProblem.h, include/base/NekRSProblemBase.h, src/base/NekRSProblem.C, src/base/NekRSProblemBase.C
This moves the `minimize_transfer_in/out` feature into the `NekRSProblemBase` so that we don't need to repeat the same logic inside the up-and-coming `NekRSStandalonProblem`.
fyi @ahuxford
=> Move minimize transfer feature into NekRS base class.

doc/content/source/problems/OpenMCCellAverageProblem.md, include/base/OpenMCCellAverageProblem.h, src/base/OpenMCCellAverageProblem.C, test/tests/openmc_errors/tallies/separate_tallies.i, test/tests/openmc_errors/tallies/tests
For problems with many tallies that are just added automatically by Cardinal, we can get a big speedup if assuming those tallies are spatially separate. I tested this with the Radiant unit cell geometry, and got active batch particle rates to roughly double by leveraging the fact that the tallies are spatially separate.
Closes #331
=> Add option to assume separate tallies.

include/base/OpenMCCellAverageProblem.h, src/base/OpenMCCellAverageProblem.C
Updating calls to `setContainedCells` for a hint to be passed to OpenMC to accelerate the search for a cell's upward path through the geometry. Further description of the need for this can be found here: 
openmc-dev/openmc#1966
This also updates the OpenMC submodule to a version that includes this new optimization.
=> Adjusting calls to setContainedCells for new optimization in OpenMC

doc/config.yml, doc/content/news.md, doc/content/news/feb2022.md, tutorials/gas_compact_multiphysics/openmc_nek.i
Unnecessary duplicate transfer in one of the tutorials.
=> Remove redundant transfer from tutorial

doc/content/start.md
Multiple people (myself included) have encountered an error when running the test suite due to not finding `libmesh-config`. This adds some instructions for how to fix the error.
=> Add additional error help for finding libmesh-config

doc/content/start.md
Fix instructions for `METHOD` vs. `METHODS` on the Cardinal build page.
Thanks @milljm and @loganharbour for helping diagnose this mistake!
=> Correct METHOD vs. METHODS discussion.

include/base/OpenMCCellAverageProblem.h, include/base/OpenMCProblemBase.h, src/base/OpenMCCellAverageProblem.C, src/base/OpenMCProblemBase.C
Cardinal currently tracks the element phase in order to give some error messages to the user; in preparation for a future distributed mesh implementation, this PR just reorganizes these to calculate phase on the fly and store phase based on the cell (instead of the element).
=> Replace some data structures for element phases

include/base/OpenMCCellAverageProblem.h, src/base/OpenMCCellAverageProblem.C
This PR adds a data structure that stores one point within each cell; this will be needed when moving to a distributed mesh implementation, because the ranks will still need to all call lookup routines in OpenMC for points that may not be in their decomposition.
=> Store one point in each cell.

tutorials/pebbles/tests
These tests don't need so many resources, so we can let them run on more systems by reducing these requirements.
=> Reduce parallel test requirements.

test/tests/neutronics/source/mesh.i, test/tests/neutronics/source/openmc.i, test/tests/neutronics/source/tests
This PR puts a mesh generator sequence in one OpenMC test into a file so that the test can run properly with a distributed mesh. There is a bug somewhere in one of the mesh generators that just seg faults when trying to use with distributed mesh.
=> Put mesh behind file mesh generator to allow distributed mesh

Makefile, doc/content/start.md
These changes will now not *require* you to set `HDF5_ROOT` - instead, we will try and use the HDF5 that PETSc downloads, and otherwise use whatever is set in `HDF5_ROOT`.
=> Simplify hdf5 detection

doc/content/start.md
Users sometimes get confused with the instructions printed to test out the PETSc installation, because it's not clear that you have to change working directories to properly run the test suite.
=> Clarify instructions for PETSc tests

include/base/OpenMCProblemBase.h, src/base/OpenMCProblemBase.C, test/tests/neutronics/heat_source/from_postprocessor.i, test/tests/neutronics/heat_source/tests
For time-dependent simulations, the power used to normalize the OpenMC tallies should vary with time. This PR allows a postprocessor to be provided for `power`. No syntax changes are needed if you still want to set power with a Real value, like `power = 100.0`. 
Closes #384
=> Allow power to be provided by a postprocessor

include/utils/HexagonalLatticeUtility.h, src/utils/HexagonalLatticeUtility.C, unit/src/HexagonalLatticeTest.C
If a point falls *exactly* on a gap plane, the `HexagonalLatticeUtility` will sometimes fail to assign that point to a channel. This changes the logic so that if a point fails to fall inside a polygon, we also explicitly check whether its distance is very close to an edge of that polygon.
=> Revise hexagonal utility logic

config/check_deps.mk
This should help eliminate mistakes where the submodules are not pointing to the versions tied to the repository.
=> Add warnings if the MOOSE, OpenMC, or NekRS submodules are out of date.

doc/content/start.md
removed $ from beginning of commands to be copied, so user can copy/paste without having to delete the $
=> start.md cleanup

doc/content/nek_tools.md, doc/content/start.md
Users of the NekRS wrapping will often want to use the Nek5000 tool scripts (`exo2nek`, `visnek`, etc.). This adds instructions to the Cardinal website to help streamline the process.
=> Add check install step for the NekRS scripts.

src/base/OpenMCProblemBase.C, test/tests/openmc_errors/no_range/geometry.xml, test/tests/openmc_errors/no_range/make_openmc_model.py, test/tests/openmc_errors/no_range/materials.xml, test/tests/openmc_errors/no_range/openmc.i, test/tests/openmc_errors/no_range/settings.xml, test/tests/openmc_errors/no_range/tests
This adds a warning message if the user does not set the `settings.temperature.range` in an OpenMC model. If the user sets the temperature of some cells in their `geometry.xml` file, OpenMC is going to load a set of nuclear data files according to those temperatures. During the course of the multiphysics simulation, Cardinal likely could set a temperature outside that already-loaded range. 
For efficiency purposes, the only check that OpenMC makes when setting a cell temperature is to check that the temperature is within the global min/max of the loaded data (`openmc::settings::temperature_min/max`), which could be different from precisely what was loaded for a particular nuclide. 
Disclaimer: I was NOT able to reproduce this with just the C-API. I can't explain that, but I'm happy with …
=> Add warning for user if they do not set temperature_range.

scripts/plot_nek_logfile.py
For periodic flow cases, special logic needs to be taken to extract the bulk pressure drop. This adds the bulk pressure drop to the temporal convergence criteria plots.
=> Add bulk pressure drop to temporal convergence plots

doc/content/source/problems/OpenMCCellAverageProblem.md, doc/content/tutorials/pincell1.md, include/base/OpenMCCellAverageProblem.h, src/base/OpenMCCellAverageProblem.C, test/tests/neutronics/mesh_tally/one_mesh_no_input_file.i, test/tests/neutronics/mesh_tally/tests, tutorials/lwr_solid/openmc_um.i
This PR corresponds to [an OpenMC PR](https://github.com/openmc-dev/openmc/pull/2137) that added a constructor to OpenMC to create a mesh form a libMesh pointer. A Cardinal simulation can access the pointer of a libMesh mesh and modify it appropriately during simulations, as opposed to creating/reading a mesh input file. This will help facilitate adaptive mesh refinement simulations, as well as core thermal expansion simulations.
=> Allowing OpenMCCellAverageProblem.C to use a libMesh pointer or mesh file during a simulation

doc/content/source/problems/OpenMCCellAverageProblem.md, include/base/CardinalEnums.h, include/base/OpenMCCellAverageProblem.h, include/postprocessors/FissionTallyRelativeError.h, src/base/CardinalEnums.C, src/base/OpenMCCellAverageProblem.C, src/postprocessors/FissionTallyRelativeError.C, test/tests/neutronics/feedback/lattice/gold/damage_energy_out.csv, test/tests/neutronics/feedback/lattice/gold/fission_q_prompt_out.csv, test/tests/neutronics/feedback/lattice/gold/fission_q_recoverable_out.csv, test/tests/neutronics/feedback/lattice/gold/heating_local_out.csv, test/tests/neutronics/feedback/lattice/gold/heating_out.csv, test/tests/neutronics/feedback/lattice/openmc_scores.i, test/tests/neutronics/feedback/lattice/tests
To support fixed source mode, we will want Cardinal to support other tally scores to couple to MOOSE. This adds an enumeration for the available tally scores:
- `heating`
- `heating-local`
- `kappa-fission` (default)
- `fission-q-prompt`
- `fission-q-recoverable`
- `damage-energy`
I just added all the scores that have units of eV/particle. Most of the changes in this PR are just removing specific code comments/changing member variables names to not be so specific to a kappa fission score. The only notable changes are:
- adding the new scores, plus tests
- being sure to only use the "does the cell have fissionable material?" check for the `kappa-fission`, `fission-q-prompt` and `fission-q-recoverable` scores
=> Enable different tally scores for heating

include/base/OpenMCCellAverageProblem.h, include/base/OpenMCProblemBase.h, src/base/OpenMCCellAverageProblem.C, src/base/OpenMCProblemBase.C, test/tests/neutronics/fixed_source/gold/overlap_all_out.csv, test/tests/neutronics/fixed_source/gold/overlap_solid_out.csv, test/tests/neutronics/fixed_source/overlap_all.i, test/tests/neutronics/fixed_source/overlap_solid.i, test/tests/neutronics/fixed_source/settings.xml, test/tests/neutronics/fixed_source/tests, test/tests/openmc_errors/fixed_source/k.i, test/tests/openmc_errors/fixed_source/k_trigger.i
This PR adds a fixed source mode to Cardinal (this PR is rebased off of #439, and will be updated once that is merged). The only major difference is how the tallies are normalized. Instead of preserving a user-specified power level, the tally results are converted to power by:
tally (eV / particle) * source_strength (particles / s) * Joule / eV
=> Fixed source mode

include/base/OpenMCCellAverageProblem.h, src/base/OpenMCCellAverageProblem.C, test/tests/neutronics/feedback/different_units/tests, test/tests/neutronics/feedback/lattice/tests, test/tests/neutronics/feedback/single_level/tests, test/tests/neutronics/relaxation/cell_tallies/tests, test/tests/neutronics/relaxation/mesh_tallies/tests, test/tests/openmc_errors/adaptivity/fixed_mesh.i, test/tests/openmc_errors/adaptivity/geometry.xml, test/tests/openmc_errors/adaptivity/materials.xml, test/tests/openmc_errors/adaptivity/settings.xml, test/tests/openmc_errors/adaptivity/tests
For adaptive mesh refinement, we will need to re-establish the mapping from OpenMC cells to the [Mesh] between each solve. This provides some of the machinery to do this (while still missing the ability to delete tallies + re-add them; see [this issue](https://github.com/openmc-dev/openmc/issues/2155) for the relevant changes in OpenMC). 
This PR checks correctness by setting `fixed_mesh = false` to a few representative tests to make sure that re-evaluating the mapping doesn't change the results when the [Mesh] isn't changing (which it should not).
Refs #449
=> Reset mapping of cells-to-elems between solves

src/base/OpenMCCellAverageProblem.C, test/tests/nek_standalone/ethier/tests, test/tests/neutronics/mesh_tally/tests, test/tests/openmc_errors/zero_tally/geometry.xml, test/tests/openmc_errors/zero_tally/materials.xml, test/tests/openmc_errors/zero_tally/openmc.i, test/tests/openmc_errors/zero_tally/settings.xml, test/tests/openmc_errors/zero_tally/tests, test/tests/userobjects/hexagonal_gap_layered/tests, test/tests/userobjects/sideset_layered/tests, test/tests/userobjects/subchannel_layered/tests, tutorials/lwr_solid/tests, tutorials/pincell_multiphysics/tests, tutorials/transfers/tests
Distributed mesh testing is now enabled on CIVET; this PR makes a few minor fix-ups to tests that can only run in replicated meshes that we previously weren't explicitly restricting so.
Also adds a check that tallying OpenMC on a MooseMesh cannot work with distributed meshes, since OpenMC always replicates the mesh on each MPI rank internally.
=> Enable distributed mesh testing

include/base/OpenMCCellAverageProblem.h, src/base/OpenMCCellAverageProblem.C, test/tests/neutronics/heat_source/distrib_cell/tests
This PR simplifies the tally setup in Cardinal by always adding tallies where the user requests them, even if the tally would technically be zero in those regions.
This also adds a few minor helper functions that will be useful when we support multiple tally scores.
Closes #452
=> Simplify tally setup

doc/content/news/mar2022.md, doc/content/source/problems/OpenMCCellAverageProblem.md, doc/content/tutorials/convergence.md, doc/content/tutorials/openmc_fluid.md, include/base/OpenMCCellAverageProblem.h, src/base/OpenMCCellAverageProblem.C, test/tests/neutronics/mesh_tally/fission_tally_std_dev.i, test/tests/neutronics/relaxation/cell_tallies/output_fission_tally.i, test/tests/neutronics/relaxation/mesh_tallies/output_fission_tally.i, test/tests/openmc_errors/tallies/output_name_length.i, test/tests/openmc_errors/tallies/tests, test/tests/postprocessors/fission_tally_relative_error/openmc.i, tutorials/gas_assembly/openmc.i, tutorials/gas_compact/openmc.i, tutorials/gas_compact_multiphysics/openmc_nek.i, tutorials/gas_compact_multiphysics/openmc_thm.i, tutorials/pincell_multiphysics/openmc.i
This PR adds a parameter `output_name` that lets the user select the auxiliary variable name to use for any additional OpenMC tally outputs, such as the standard deviation and value of the _unrelaxed_ tally. I also changed the names of the enum flags to be more descriptive and agnostic of whether the tally represents a fission heat source, in preparation for upcoming PRs that will allow us to tally quantities that don't have a conventional notion of "power density," such as flux.
=> Allow custom variable names for tally outputs

src/base/OpenMCCellAverageProblem.C
We recently added the ability to automatically select the name for additional outputs specified for `OpenMCCellAverageProblem` (such as for writing the tally standard deviation). However, the names are printed in uppercase because that's how the enum is converted to a string, and I think lowercase looks better and is more in line with all the other lowercase variables within `OpenMCCellAverageProblem`.
=> Use lowercase name for default names

doc/content/faq.md
When trying to run tests without the conda environment, libmesh's default installation is `cardinal/contrib/moose/libmesh/installed`, not `cardinal/contrib/moose/libmesh`. 
Using the LIBMESH_DIR in FAQ results in same libmesh-config error message as without the env variable declared.
Correcting LIBMESH_DIR to the '.../installed' directory removes the error and allows for the tests to build and run.
- Tested on Nek5k cluster
=> Update faq.md for running tests without conda.

include/base/NekInterface.h, src/base/NekInterface.C, src/base/NekRSProblem.C
This adds the ability for the user to easily control the tolerances for checking energy conservation between MOOSE and NekRS (which were previously hard-coded).
Closes #498
=> Support user-defined Nek tolerances

doc/content/checking_install.md
@vincemilo kindly pointed out that the instructions we provide users to check their OpenMC install aren't fully complete. With the particular tutorial we were telling users to run, you need to first create the mesh by running another input file. This is spelled out clearly on the tutorial documentation page, but not on our "getting started" page.
For simplicity, this just changes the input file we tell users to run.
=> Use input file that new users can actually run without prep steps.

include/base/NekRSProblemBase.h, include/base/OpenMCProblemBase.h, src/base/NekRSProblem.C, src/base/NekRSProblemBase.C, src/base/OpenMCCellAverageProblem.C, src/base/OpenMCProblemBase.C, test/tests/conduction/boundary_and_volume/prism/tests, test/tests/deformation/vol-areas/nek.i, test/tests/nek_errors/invalid_field/auxvar.i, test/tests/nek_errors/invalid_field/nonlinear.i, test/tests/nek_errors/invalid_field/tests, test/tests/neutronics/feedback/lattice/tests
Cardinal automatically creates a number of auxiliary variables to facilitate coupling. This can be confusing for new users who mistakenly think they need to create these variables themselves. This PR throws an explicit error telling the user that the name of their aux variable is already reserved for Cardinal.
=> Throw error if user specifies a duplicate variable

include/base/NekInterface.h, include/mesh/NekRSMesh.h, src/base/CardinalApp.C, src/base/NekInterface.C, src/mesh/NekRSMesh.C
This reverts the recent MOOSE changes that cause unused parameters to error. It also adds another commit that sets up unique block IDs for the solid and fluid regions in NekRS CHT cases.
fyi @anshchaube  once this is merged the unused parameter errors will go away.
=> Ignore unused params

include/base/OpenMCCellAverageProblem.h, src/base/OpenMCCellAverageProblem.C
This PR refactors the functions in `OpenMCCellAverageProblem` that write an OpenMC tally to MOOSE. Previously, we had separate functions that wrote either the relaxed or unrelaxed version of the same tally. In order to prepare for future capabilities where we'll have multiple scores on each tally, it's a good idea to merge these functionalities to get simpler code.
=> Refactor tally functions

include/base/NekRSProblem.h, include/base/NekRSProblemBase.h, include/base/NekRSSeparateDomainProblem.h, src/base/NekRSProblem.C, src/base/NekRSProblemBase.C, src/base/NekRSSeparateDomainProblem.C
Now that we have quite a few different data mappings from MOOSE into NekRS (heat flux, volumetric heat source, x/y/z displacements), we can reduce some duplicate code by creating helper functions that establish the mapping from MOOSE nodal points to NekRS's GLL points.
=> Refactor data mapping from MOOSE to Nek

include/utils/GeometryUtility.h, src/utils/GeometryUtility.C, unit/src/GeometryUtilityTest.C
Adds a function to get the corner coordinates of a bounding box with an additional length scaling. Supports #535
=> Add boxCoords function to geometry utility.

include/base/OpenMCCellAverageProblem.h, include/base/OpenMCProblemBase.h, src/base/OpenMCCellAverageProblem.C, src/base/OpenMCProblemBase.C, test/tests/neutronics/feedback/lattice/non_material_fluid.i, test/tests/neutronics/feedback/lattice/tests, test/tests/openmc_errors/cell_instances/insufficient_materials/tests
This adds a table print to show which subdomains map to which OpenMC materials. For a subdomain A, this will display to the user the set of OpenMC materials that the elements in the subdomain map to; the purpose is to help clarify model setup for the user, as well as add infrastructure for later DAGMC models where we're going to impose that each subdomain should map to only 1 OpenMC material (this can be a sanity check on model setup).
=> Get mapping from subdomains to OpenMC materials

include/base/NekInterface.h, src/base/NekRSSeparateDomainProblem.C
`NekRSProblem` sets values in an `indices` data structure to make the data writing in the user scratch space a bit more human-readable. This will replace `4 * scalarFieldOffset()` by `indices.boundary_scalar02` (or whatever that slot in the scratch space physically represents).
This PR just makes `NekRSSeparateDomainProblem` consistent with `NekRSProblem`'s approach. This is a necessary prerequisite to integrating NekRS with the MOOSE stochastic tools module, because we're going to have additional scratch space slots and it'll be easier to design that system once everything in Cardinal is self-consistent.
=> Use consistent indices data structure for mapping to scratch space. 

src/base/OpenMCCellAverageProblem.C
This PR fixes error code which previously would not throw an error if the user forgot to specify the cell level.
=> Fix error catching when user needs either level or lowest

include/base/OpenMCCellAverageProblem.h, include/base/OpenMCProblemBase.h, src/base/OpenMCCellAverageProblem.C, src/base/OpenMCProblemBase.C
To help integrate DAGMC into our cell-coupling, this moves some functionality from `OpenMCCellAverageProblem` up to the base class.
=> Refactoring to simplify OpenMCCellAverageProblem

src/base/OpenMCCellAverageProblem.C
We use a tolerance of 1e-6 to check that the tally sums to the user-specified power, so we should be using the same tolerance to check that the global and local tally sums match.
=> Use same tolerance as for local vs. global match

include/base/OpenMCProblemBase.h, src/base/OpenMCCellAverageProblem.C, src/base/OpenMCProblemBase.C, test/tests/neutronics/void/geometry.xml, test/tests/neutronics/void/make_openmc_model.py, test/tests/neutronics/void/materials.xml, test/tests/neutronics/void/openmc.i, test/tests/neutronics/void/settings.xml, test/tests/neutronics/void/tests, test/tests/openmc_errors/densities/void_density.i
For single-level geometries, we currently throw a warning to the user if their OpenMC model contains additional cells that weren't coupled to MOOSE. For DagMC models, there will typically be an implicit complement cell (VOID material), which will be uncoupled to MOOSE. This can be misleading to the user if they mistakenly think they are missing coupling for one cell, even if that cell is void and it would never receive feedback anyways.
This PR excludes void cells from the warning messages shown to users, as well as adds a table to show more information about neglected cells.
=> Better warnings for single-level geometries

doc/content/source/auxkernels/PointTransformationAux.md, doc/content/source/problems/OpenMCCellAverageProblem.md, doc/content/source/userobjects/SymmetryPointGenerator.md, include/base/OpenMCCellAverageProblem.h, include/userobjects/SymmetryPointGenerator.h, src/base/OpenMCCellAverageProblem.C, src/userobjects/SymmetryPointGenerator.C, test/tests/neutronics/symmetry/openmc.i, test/tests/neutronics/symmetry/rotational/openmc.i, test/tests/neutronics/symmetry/tests, test/tests/neutronics/symmetry/triso/openmc.i, test/tests/neutronics/symmetry/wrong_uo.i, test/tests/symmetry/reflection.i, test/tests/symmetry/rotation.i, test/tests/userobjects/symmetry_point_generator/test.i, test/tests/userobjects/symmetry_point_generator/tests, unit/include/SymmetryPointGeneratorTest.h, unit/src/SymmetryPointGeneratorTest.C
As I'm increasing the complexity of the OpenMC wrapping, some functionality should be moved into other classes to better encapsulate them. This moves the `SymmetryPointGenerator` from a general C++ class to a `UserObject`, so that all the logic on input parameters can be moved out of `OpenMCCellAverageProblem`.
=> Move symmetry operation into a user object

include/base/NekRSProblemBase.h, src/base/NekRSProblemBase.C
I frequently debug input files by running each app separately, which can be inconvenient if we have some `mooseErrors` which throw only when NekRS is the main app. This softens the error to a warning.
=> Allow warning for synchronization_interval.

include/base/OpenMCCellAverageProblem.h, src/base/OpenMCCellAverageProblem.C, src/base/OpenMCProblemBase.C, test/tests/neutronics/relaxation/cell_tallies/tests, test/tests/neutronics/relaxation/mesh_tallies/tests
If the `[Mesh]` is changing (from adaptivity or spatial deformation), then the tallies created by Cardinal need to be erased and re-created. For mesh tallies, this is obvious because we are tallying on the `[Mesh]`. For cell tallies, it is unlikely, but possible that as the `[Mesh]` changes that new cells are "exposed" to the coupling (because we only add tallies to fissile cells that map to some MOOSE elements). In this case, we'd need to add those cells to the cell instance filter.
These changes simply (i) delete the local and global tallies, (ii) delete the tally filters, and (iii) delete the meshes (if using mesh tallies), then re-creates them. I tested this by turning on this step-by-step regeneration on an existing test, to check that this has no influence on the results. 
The other …
=> Reset tallies between Picard iterations

doc/content/source/problems/NekRSProblem.md, doc/content/source/problems/NekRSSeparateDomainProblem.md, doc/content/source/problems/seg_fault_warning.md, src/base/NekRSProblem.C, src/base/NekRSSeparateDomainProblem.C, test/tests/conduction/identical_volume/cube/cube.udf, test/tests/conduction/nonidentical_volume/cylinder/cylinder.udf, test/tests/conduction/nonidentical_volume/nondimensional/cylinder.udf, test/tests/deformation/mesh-velocity-areas/pipe.oudf, test/tests/deformation/mesh-velocity-nondimensional/pipe.oudf, test/tests/deformation/simple-cube/nekbox.udf, test/tests/nek_errors/insufficient_scratch/brick.par, test/tests/nek_errors/insufficient_scratch/brick2.par, test/tests/nek_errors/insufficient_scratch/tests
This FY we are adding support for Nek to interface with MOOSE's stochastic tools module. This means that we need to add another "slot" to `nrs->usrwrk` to hold that incoming information. If we were to keep our current convention where the "ordering" in `nrs->usrwrk` never changes, this means that we're going to end up with quite a lot of unused space allocated (e.g. the first 6 slots) if we only are interested in stochastic modeling.
This PR changes our convention to NOT retain the same order in `nrs->usrwrk` all the time. In other words, if there is a slot in `nrs->usrwrk` that a particular case does not need, we shift all the other slots forward by one, so that there's no "unused gaps" in this array.
I _think_ I caught all places in the documentation and test suite where we need to …
=> Allow different orders in bc->wrk

include/base/CardinalProblem.h, include/base/NekRSProblemBase.h, include/base/OpenMCProblemBase.h, src/base/CardinalProblem.C, src/base/NekRSProblemBase.C, src/base/OpenMCProblemBase.C
This disables a bunch of user parameters inherited from MOOSE which don't actually do anything, but give the impression that there's lots of extra documentation on the MooseDocs website.
=> Add base class to disable unused parameters.

include/base/OpenMCCellAverageProblem.h, src/base/OpenMCCellAverageProblem.C, test/tests/conduction/boundary_and_volume/prism/moose.i, test/tests/conduction/boundary_and_volume/prism/openmc.i, test/tests/conduction/boundary_and_volume/prism/openmc_exact.i, test/tests/conduction/identical_volume/cube/moose.i, test/tests/conduction/identical_volume/cube/nek_master.i, test/tests/conduction/nonidentical_volume/cylinder/moose.i, test/tests/conduction/nonidentical_volume/cylinder/nek_master.i, test/tests/conduction/nonidentical_volume/cylinder/nek_master_exact.i, test/tests/conduction/nonidentical_volume/nondimensional/nek_master.i, test/tests/deformation/simple-cube/box-test.i, test/tests/deformation/simple-cube/moose.i, test/tests/deformation/vol-areas/box-test.i, test/tests/nek_temp/exact/exact.i, test/tests/nek_temp/exact/exact_volume.i, test/tests/nek_temp/first_order/nek.i, test/tests/nek_temp/first_order/nek_volume.i, test/tests/nek_temp/second_order/nek.i, test/tests/nek_temp/second_order/nek_volume.i, test/tests/neutronics/feedback/different_units/openmc_master.i, test/tests/neutronics/feedback/different_units/openmc_master_cm.i, test/tests/neutronics/feedback/lattice/openmc_master.i, test/tests/neutronics/feedback/single_level/openmc_master.i, test/tests/neutronics/feedback/unmapped_moose/openmc_master.i, test/tests/postprocessors/nek_weighted_side_average/moose.i, test/tests/postprocessors/nek_weighted_side_integral/moose.i, test/tests/userobjects/hexagonal_gap_layered/user_component.i, test/tests/userobjects/subchannel_layered/user_component.i
Users are sometimes confused when they see that `density` or `temp` are defined everywhere over the `[Mesh]`, when only a subset of those values get set into OpenMC (depending on what they set for `solid_blocks` and `fluid_blocks`). This PR now block-restricts the `temp` and `density` variables so that behavior is clearer.
Also took the opportunity to remove some soon-to-be-deprecated syntax.
=> Block restrict temperature and density

include/auxkernels/CartesianGrid.h, src/auxkernels/CartesianGrid.C
This can be used to more easily specify bin boundaries for skinning.
=> Add optional shift to grid values.

src/base/OpenMCProblemBase.C
This fixes a runtime error when cardinal is compiled with clang. The error looks like this:
```
libMesh terminating:
basic_string
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
[unset]: PMIU_write error; fd=-1 buf=:cmd=abort exitcode=1 message=application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
:
system msg for write_line failure : Bad file descriptor
```
Refs #0
=> Convert int into string

test/tests/cht/nondimensional/exodiff.cmp, test/tests/cht/nondimensional/tests
We have one test which is failing with the next release of NekRS. The test is only failing for some postprocessors on pressure, because this particular test does not get to a stable pressure solve regime (e.g. beyond the initial transient behavior). Expanding the test to reach the pseudo-steady state shows very similar physics predictions among the current NekRS version and the next release, so we can reasonably conclude that these diffs are just due to changes in how NekRS inintializes the pressure field/other solver-related things which are sensitive on the first few time steps.
In other words, this PR changes the `cht/nondimensional/sfr_pincell` test so that we simply don't compare pressure, because it is not a meaningful/reliable quantity to compare anyways.
=> Remove pressure from test.

include/mesh/NekRSMesh.h, src/mesh/NekRSMesh.C, test/tests/deformation/mesh-velocity-areas/pipe.i, test/tests/deformation/mesh-velocity-nondimensional/pipe.i
For CHT, NekRS numbers all the fluid elements with lower element IDs than all of the solid elements. This sorting exists on each RANK, but previously we were doing this assignment of subdomain IDs only on the global data. In other words, we were not correctly labeling elements in the solid vs. fluid mesh - it worked in serial, but wasn't computing the total number of fluid elements for parallel runs. This fixes that error.
=> Correct fluid/solid block numbering

include/base/OpenMCProblemBase.h, src/base/OpenMCProblemBase.C
We used to throw a warning if the user adds tallies to a non-fissile region. But now that we support much more general tallies like `flux` or `heating-local`, we didn't need this anymore. Somehow, this function lingered around in the code, so this removal isn't changing any functionality - just tidying up.
=> Remove unused function for fissile materials.

include/postprocessors/NekPostprocessor.h, src/postprocessors/NekPostprocessor.C, src/postprocessors/NekSideAverage.C, src/postprocessors/NekSideIntegral.C, src/postprocessors/NekVolumeIntegral.C, src/postprocessors/ReynoldsNumber.C
This removes `_fixed_mesh` for simplicity - the cost savings from this is negligible, so it's not worth the extra code complexity.
=> Remove fixed_mesh from postprocessors

include/base/CardinalEnums.h, include/base/NekInterface.h, include/base/NekRSSeparateDomainProblem.h, include/postprocessors/NekPostprocessor.h, src/base/CardinalEnums.C, src/base/NekInterface.C, src/base/NekRSSeparateDomainProblem.C, src/postprocessors/NekPostprocessor.C, src/postprocessors/NekPressureSurfaceForce.C, test/tests/nek_separatedomain/invalid_params/tests, test/tests/nek_standalone/conj_ht/tests
If the `nek_mesh` parameter can only ever take a single valid value for `NekRSSeparateDomainProblem`, it may be confusing for users to see it in the documentation (which implies they could set some other value besides "fluid").
=> Remove nek_mesh parameter from NekRSSeparateDomainProblem

scripts/job_summit
Updates the Summit job script to better support OpenMC-only cases, but not erroring out if various NekRS case files are missing.
=> Update Summit job script

doc/content/hpc.md, scripts/job_bebop
This updates to GCC >= 9.0 for the upcoming NekRS release.
=> Update Bebop instructions

src/mesh/NekRSMesh.C, test/tests/nek_separatedomain/transfers_temperature/cardinal_sub.i
We do not need to call `createMesh` if the internal nekRS mesh is already second-order, so we can save some effort.
=> Only create 2nd order mesh if not already 2nd order

doc/content/tutorials/cht1.md, include/base/NekInterface.h, src/base/NekInterface.C, src/postprocessors/NekPostprocessor.C, src/postprocessors/NekSideExtremeValue.C, src/postprocessors/NekVolumeExtremeValue.C, tutorials/fhr_reflector/cht/solid.i, tutorials/fhr_reflector/conduction/solid.i
This consolidates the `sideMinValue` and `sideMaxValue` postprocessors in NekRS together into a single extreme-value postprocessor. A similar consolidation is done for the volume-based postprocessors.
Also added some minor documentation enhancements to the FHR reflector block tutorial.
=> Consolidate extreme value postprocessors

tutorials/gas_compact/unit_cell.py, tutorials/gas_compact_multiphysics/unit_cell.py
The `face_centered` option should not be used in these two tutorials - that's an artifact of how we originally made these files through the Center of Excellence.
=> Simplify tutorial options

Makefile, src/base/OpenMCProblemBase.C
When debugging a model, users sometimes forget to set ICs for properties in the `.i` MOOSE file. This adds an extra string to error messages to point them towards a good debugging option.
=> Add help message about properties

doc/content/source/problems/OpenMCCellAverageProblem.md
Closes #750. 
Looking for some advice on fixing the italics for the [html version of the docs](https://cardinal.cels.anl.gov/source/problems/OpenMCCellAverageProblem.html#:~:text=_division%20by%20a%20volume_).
=> Small typos in OpenMCCellAverageProblem documentation 

config/check_nekrs.mk
This can help users to more clearly identify when they have NEKRS_HOME pointing somewhere incorrect.
=> Add more info to NEKRS_HOME error

src/base/NekRSProblemBase.C
A user was recently confused on what "unused" meant in the usrwrk scratch space table that Cardinal prints out. This adds clarification that the space has indeed been allocated, but Cardinal isn't already using it.
=> Add extra info about unused interpretation

doc/content/tutorials/convergence.md, scripts/inactive_study.py
This PR closes #577. It provides the user three options for detecting convergence using Shannon entropy. All methods assess the standard deviation and mean for some set of entropy values. If the current batch's entropy value is within one standard deviation of the mean (of the specified number of batches), it will report this batch number and recommend using at least this many inactive cycles. 
I tested this locally for a case with multiple layers for each detection type, and it went smoothly. If desired, I can provide the example, but I don't think those files need to be pushed. The script is setup to work assuming a user provides the appropriate arguments and input files, so other developers can test that this works locally using their own Cardinal simulation if desired.
=> Detecting Convergence of the Fission Source via Shannon Entropy

doc/content/compiletime.md
Sometimes when rebuilding after significant source code changes, there are conflicts with a prior build that manifest as linking errors. I added some tips to the [compile time trouble shooting](https://cardinal.cels.anl.gov/compiletime.html), which is linked on [building without conda page](https://cardinal.cels.anl.gov/without_conda.html), to help users resolve this issue.
Closes #823
=> Documentation troubleshooting tip added

doc/content/tutorials/cht.md, doc/content/tutorials/cht1.md, doc/content/tutorials/cht2.md, doc/content/tutorials/cht3.md, doc/content/tutorials/cht4.md, doc/content/tutorials/cht5.md, doc/content/tutorials/dagmc.md, doc/content/tutorials/gas_compact.md, doc/content/tutorials/openmc_fluid.md, doc/content/tutorials/openmc_solid.md, doc/content/tutorials/pincell1.md, doc/content/tutorials/pincell_multiphysics.md, doc/content/tutorials/steady_hc.md, doc/content/tutorials/triso.md, doc/content/tutorials/triso_multiphysics.md, tutorials/gas_assembly/assembly.py, tutorials/gas_compact/unit_cell.py, tutorials/gas_compact_multiphysics/unit_cell.py
Closes #831. I also noticed that MOOSE renamed the Heat Conduction Module to Heat Transfer Module, so I changed all the instances in the tutorial docs so we're up to date with MOOSE.
=> Tutorial improvements

scripts/get-dependencies.sh
Path printed in `get-dependencies.sh` was incorrect for NEKRS_HOME hint
=> fix path printed by get-dependencies

doc/content/hpc.md
Not sure why, but the website was not rendering the Frontier instructions correctly unless I moved Eddy to the bottom of the HPC page.
=> move Eddy to bottom

Makefile, doc/content/index.md, doc/content/news/december2022.md, doc/content/tutorials/nekrs_outputs.md, test/tests/bison_coupling/bison_master/bison.i, test/tests/bison_coupling/bison_sub/bison_sub.i
refs https://github.com/idaholab/moose/issues/25584
for the heat conduction -> heat transfer commit, I did this change:
"MOOSE heat conduction" -> "MOOSE heat transfer"
if this is still too much (as you often just refer to the actual heat conduction equation, and not the module), I can narrow it down a bit, or drop the commit. it s not really a priority
=> Rename tensor mechanics module

include/base/OpenMCCellAverageProblem.h, src/base/OpenMCCellAverageProblem.C, src/userobjects/OpenMCVolumeCalculation.C, test/tests/neutronics/mesh_tally/tests, test/tests/openmc_errors/block_mappings/no_blocks.i, test/tests/openmc_errors/block_mappings/tests
If a user accidentally typed in a block name which does not exist in the mesh, we used to try to convert that back to a subdomain ID before printing an error message, but this ends up giving some error code in MOOSE (665335) for the subdomain name because (of course) the block didn't exist in the first place and therefore didn't have a valid ID to begin with.
Now, we print the block name instead, for better debugging.
=> display block name in errors

doc/content/tutorials/cht2.md, doc/content/tutorials/cht5.md, doc/content/tutorials/convergence.md, doc/content/tutorials/dagmc.md, doc/content/tutorials/gas_compact.md, doc/content/tutorials/msfr.md, doc/content/tutorials/nek_intro.md, doc/content/tutorials/nekrs_outputs.md, doc/content/tutorials/nekrs_standalone.md, doc/content/tutorials/nekrs_stochastic.md, doc/content/tutorials/openmc_fluid.md, doc/content/tutorials/other_apps.md, doc/content/tutorials/pincell1.md, doc/content/tutorials/pincell_multiphysics.md, doc/content/tutorials/restart_nek_moose.md, doc/content/tutorials/transfers.md, doc/content/tutorials/triso.md, doc/content/tutorials/triso_multiphysics.md, doc/content/tutorials/volumetric.md, include/base/OpenMCCellAverageProblem.h, src/base/OpenMCCellAverageProblem.C
Historically, we designed the feedback into OpenMC for solids (temperature only) and fluids (temperature and density). However, the code could be cleaner and easier to understand if we also allowed density-only feedback. This PR just makes some 1:1 internal member variable name changes to remove the notion of solid vs. fluid.
=> Change internal class names to prepare for upcoming density-only feedback

include/base/OpenMCCellAverageProblem.h, src/base/CardinalApp.C, src/base/OpenMCCellAverageProblem.C
For legacy reasons, we had a table print of the fractional power values of the tallies added by Cardinal. I think the additional code complexity here is no longer worth it (this was really added mostly to help with debugging the tally coding when Cardinal was first being developed). 
Arguments in favor of removing this code:
- The fractional power values can be obtained through alternate input file syntax in MOOSE
- These tables can be extremely long for most realistic OpenMC models, desensitizing the user to the console output
- We had to have some additional logic to decide _which_ tallies to output this for, since there's not a natural analog to a fractional "flux" (and this is one score we support)
=> Remove table print of fractional power values.

doc/content/hpc.md, scripts/job_sawtooth
Closes #876. Open to feedback on the docs comments/submit script.
Also, is there a reason we load `cmake` in the job launch script? Does the cardinal executable need `cmake` to execute the job? I'd think no, but I am not an expert in that department
=> sawtooth docs extra info and launch script adjustment

src/base/OpenMCCellAverageProblem.C, test/tests/neutronics/photon/geometry.xml, test/tests/neutronics/photon/materials.xml, test/tests/neutronics/photon/openmc.i, test/tests/neutronics/photon/settings.xml, test/tests/neutronics/photon/tests
Thanks Shikhar for noting this incompatibility! Photon heating scores cannot be used with tracklength estimators due to some approximations made for thick-target bremmstrahlung.
=> Enforce collision estimator for photon heating.

utils/meshes/assembly/convert.i, utils/meshes/assembly/mesh.py, utils/meshes/assembly/mesh_settings.py, utils/meshes/interassembly/convert.i, utils/meshes/interassembly/mesh.py, utils/meshes/interassembly/mesh_settings.py, utils/meshes/interassembly_w_structures/convert.i, utils/meshes/interassembly_w_structures/mesh.py, utils/meshes/interassembly_w_structures/mesh_settings.py
For the meshing scripts, for some reason we had one user-defined setting (`corner_smoothing`) which was not defined in the `mesh_settings.py`. This moves everything into this file for consistency.
=> move all mesh parameters into mesh_settings

include/base/OpenMCProblemBase.h, src/base/OpenMCCellAverageProblem.C, src/base/OpenMCProblemBase.C, test/tests/neutronics/dagmc/density_skin/disjoint_bins.i, test/tests/neutronics/feedback/temperature/one_one/openmc.i, test/tests/neutronics/feedback/temperature/one_two/openmc.i, test/tests/neutronics/feedback/temperature/two_one/openmc.i, test/tests/neutronics/feedback/temperature/two_one/openmc_default.i, test/tests/neutronics/feedback/temperature/two_one/openmc_multi_temp.i, test/tests/neutronics/heat_source/default_tally_blocks.i, test/tests/neutronics/openmc_xml/skip_statepoint.i, test/tests/neutronics/openmc_xml/tests, test/tests/neutronics/solid/openmc_missing_pebble.i, test/tests/neutronics/solid/openmc_zero.i, test/tests/neutronics/triggers/k_std_dev.i, test/tests/neutronics/triggers/mesh_tally_rel_err.i, test/tests/neutronics/triggers/multi_rel_err.i, test/tests/neutronics/triggers/tally_rel_err.i, test/tests/openmc_errors/cell_instances/lattice_outer/temp.i, test/tests/openmc_errors/input_params/levels.i, test/tests/openmc_errors/input_params/tests, test/tests/symmetry/reflection.i, test/tests/symmetry/rotation.i
For some reason, the statepoint writing on Summit is really slow to the point where it's precluding my simulations. This adds an option to skip statepoint writing.
=> Allow to skip a statepoint

test/tests/cht/pebble/nek_master.i, test/tests/cht/pebble/shift/nek_master.i, test/tests/cht/pincell_p_v/nek_master.i, test/tests/cht/sfr_pincell/nek_main_vpp.i, test/tests/cht/sfr_pincell/nek_master.i, test/tests/conduction/identical_interface/cube/nek_master.i, test/tests/conduction/identical_interface/pyramid/nek_master.i, test/tests/conduction/nonidentical_volume/nondimensional/nek_master.i, test/tests/conduction/zero_flux/main_disjoint.i, test/tests/conduction/zero_flux/main_shared.i, test/tests/conduction/zero_flux/main_zero.i, test/tests/deformation/simple-cube/box-test.i, test/tests/deformation/vol-areas/box-test.i, test/tests/multiple_nek_apps/two_channels/moose.i, test/tests/multiple_nek_apps/two_channels/moose_combined.i, test/tests/nek_errors/invalid_transfer_pp/nek_master.i, test/tests/neutronics/feedback/different_units/openmc_master.i, test/tests/neutronics/feedback/different_units/openmc_master_cm.i, test/tests/neutronics/solid/openmc_master_zero.i, test/tests/userobjects/hexagonal_gap_layered/nek.i, test/tests/userobjects/hexagonal_gap_layered/nek_axial.i, test/tests/userobjects/hexagonal_gap_layered/normals/nek.i, test/tests/userobjects/hexagonal_gap_layered/normals/nek_axial.i, test/tests/userobjects/hexagonal_gap_layered/user_component.i, test/tests/userobjects/moab_skinner/expanding-cube/constant_expansion_coeff.i, test/tests/userobjects/subchannel_layered/user_component.i
MOOSE added error checking which severely slows down the nearest node transfer. Disable this error checking in our test suite, since we don't need it to match the test results.
=> Turn off search conflicts

apptainer/app_environment, apptainer/app_post_post_install, apptainer/app_test_begin
Installs the current cross sections into the cardinal container. Needed so that trainees don't need to when using a docker or apptainer container.
=> Install xs into the container

doc/content/tutorials/assembly.md
This adds a bulleted list of the sideset IDs for the assembly flow mesher documentation.
=> add list of sideset IDs to assembly flow mesher

include/base/OpenMCCellAverageProblem.h, include/tallies/CellTally.h, src/base/OpenMCCellAverageProblem.C, test/tests/neutronics/tally_system/cell_with_unmapped.i, test/tests/neutronics/tally_system/gold/cell_with_unmapped_out.csv, test/tests/neutronics/tally_system/tests
This PR fixes an improper generation of the cell to element map for the case where a subset of elements in the MOOSE mesh do not map to any cells in the OpenMC geometry, but a `CellTally` and temperature/density feedback is requested by the user. This PR also adds a new test to cover this case.
@aprilnovak
=> Fix the generation of the cell to element map

scripts/download-openmc-cross-sections.sh, scripts/get-dependencies.sh
Many people miss these instructions on the compilation to build in parallel. We can print it out when they fetch the dependencies to help them not miss them.
=> Hints for fast parallel builds

include/tallies/TallyBase.h, src/base/OpenMCCellAverageProblem.C
The addition of the filter system broke the tally debug output we dump to the console (example below after the filter system was merged):
```
--------------------------------------------------------
| Tally Name |  Tally Score  |     AuxVariable(s)      |
--------------------------------------------------------
| Heating    | kappa-fission | kappa_fission_g1_theta1 |
|            |               | kappa_fission_g1_theta2 |
|            |               | kappa_fission_g2_theta1 |
|            |               | kappa_fission_g2_theta2 |
|            |               | fission_g1_theta1       |
|            |               | fission_g1_theta2       |
|            |               | fission_g2_theta1       |
|            |               | fission_g2_theta2       |
|            |               | …
```
=> Fix the debug output we dump in the console for tallies.

include/userobjects/NekUserObject.h, include/userobjects/SpatialBinUserObject.h, src/userobjects/NekUserObject.C, src/userobjects/SpatialBinUserObject.C
Some of our user objects arbitrarily inherited from `ThreadedGeneralUserObject`, which requires overriding functions to join data across threads. We don't actually need to use this base class, and can instead inherit from `GeneralUserObject`, which would allow the NekRS user objects to be run with threading. 
@pshriwise noticed this when running a Nek case with threads -- previously, all our cases used pure MPI because that's what Nek uses, so we had not run into this before.
=> Remove threaded user object inheritance

src/postprocessors/TallyRelativeError.C
This PR updates the error messages in  `TallyRelativeError` to account for the new tally system. It also makes use of `paramError()` to add input syntax context to improve the model debugging experience.
=> Update TallyRelativeError error messages to account for the new tally system

src/auxkernels/CellVolumeAux.C, src/base/OpenMCCellAverageProblem.C, src/filters/FromXMLFilter.C, src/ics/BulkEnergyConservationIC.C, src/tallies/CellTally.C, src/tallies/MeshTally.C, src/tallies/TallyBase.C, src/userobjects/OpenMCNuclideDensities.C, src/userobjects/OpenMCVolumeCalculation.C, src/userobjects/RadialBin.C, src/userobjects/SymmetryPointGenerator.C, test/tests/neutronics/adaptivity/tests, test/tests/openmc_errors/mesh_tally/tests, test/tests/userobjects/volume_calculation/tests
This PR swaps `mooseError(...)` calls with `paramError(...)` calls where it makes sense to do so. Combined parameter errors (where two input parameters aren't compatible or something similar) don't work with the `paramError` paradigm, and so they were left as `mooseErrors`. This is a first pass over all of the generic and OpenMC objects; I haven't gone over the Nek objects to avoid any potential clashes in #987.
Annoyingly some `RunException` tests needed to be re-golded as they were failing pattern matching once the errors they tested were swapped to `paramErrors`. This is why a few test files are modified in this PR.
=> Swap mooseErrors to paramErrors

doc/config.yml, doc/content/cardinal_prereqs.md, doc/content/sqa/cardinal_cci.md, doc/content/sqa/cardinal_far.md, doc/content/sqa/cardinal_rtm.md, doc/content/sqa/cardinal_scs.md, doc/content/sqa/cardinal_sdd.md, doc/content/sqa/cardinal_sll.md, doc/content/sqa/cardinal_srs.md, doc/content/sqa/cardinal_stp.md, doc/content/sqa/cardinal_vvr.md, doc/content/sqa/index.md, doc/content/with_conda.md, doc/content/without_conda.md, doc/sqa_cardinal.yml, doc/sqa_reports.yml, test/tests/deformation/simple-cube/tests, test/tests/deformation/vol-areas/tests, test/tests/nek_errors/deformation/tests, test/tests/nek_errors/deformation/user/tests
This adds the MooseDocs software quality assurance (SQA) documents to the Cardinal website, using the MooseDocs SQA extension.
=> Add MooseDocs SQA documents to website

doc/content/tutorials/cht3.md, doc/content/tutorials/openmc_fluid.md, doc/content/tutorials/triso_multiphysics.md, test/tests/neutronics/symmetry/common_input.py, test/tests/neutronics/symmetry/rotational/common_input.py, test/tests/neutronics/symmetry/triso/common_input.py, tutorials/gas_assembly/common_input.i, tutorials/gas_assembly/openmc.i, tutorials/gas_assembly/solid.i, tutorials/gas_assembly/solid_mesh.i, tutorials/gas_assembly/tests, tutorials/gas_assembly/thm.i, tutorials/gas_compact_cht/common_input.i, tutorials/gas_compact_cht/nek.i, tutorials/gas_compact_cht/solid_nek.i, tutorials/gas_compact_cht/solid_thm.i, tutorials/gas_compact_cht/thm.i, tutorials/gas_compact_multiphysics/common_input.i, tutorials/gas_compact_multiphysics/openmc_nek.i, tutorials/gas_compact_multiphysics/openmc_thm.i, tutorials/gas_compact_multiphysics/tests
Closes #859.
Pretty sure this will not affect any of the gold files' results. LMK if you want me to run them, though.
=> Convert to !include paradigm

include/base/NekRSProblem.h, src/base/NekRSProblem.C, src/base/NekRSProblemBase.C, test/tests/cht/sfr_pincell/gold/nek_isolated_out.csv, test/tests/cht/sfr_pincell/gold/solid_dummy_out_nek0.csv, test/tests/cht/sfr_pincell/nek_isolated.i, test/tests/cht/sfr_pincell/sfr_pin.par, test/tests/cht/sfr_pincell/solid_dummy.i, test/tests/cht/sfr_pincell/tests
We can use Cardinal to apply a heat flux to NekRS, even if we don't want to run a coupled CHT case. This PR allows you to easily apply such a condition given total power (as opposed to having to convert that to a heat flux applied in `scalarNeumannConditions`).)
=> Allow initial condition to be set for `flux_integral`

test/tests/neutronics/symmetry/rotational/solid_mesh.i, test/tests/neutronics/symmetry/solid_mesh.i, test/tests/neutronics/symmetry/tests, test/tests/neutronics/symmetry/triso/solid_mesh.i
I've added a feature in MOOSE that causes --mesh-only mode to error out if an unused / misspelled parameter exists in the input - https://github.com/idaholab/moose/pull/29824
This causes some Cardinal tests to fail (https://civet.inl.gov/job/2748234/), mainly because background_block_name should be used instead of background_block_names for PatternedHexMeshGenerator.
@aprilnovak this will likely cause some re-goldings, let me know if this is the preferred option here or to remove the background_block_names parameter entirely so that re-golding is not needed.
=> Remove unused params from mesh only tests

src/base/OpenMCCellAverageProblem.C
If the problem needs to reinitialize coupling, do so on every opportunity. This was initially motivated by the idea that OpenMC would always be the first app to run, but in general that might not be the case so this will be more straightforward behavior and also support more flexible usage.
=> remove complicated reinit coupling

Makefile, doc/content/options.md, unit/Makefile
Disabling Embree and Double-Down by default due to some build errors. Currently working on resolving these.
Ref. #1129
=> Disable Double-Down and Embree by default.

scripts/get-dependencies.sh
As of late I've been working on rather sluggish internet connections, and found that running `get-dependencies.sh` would take several minutes. This PR adds the `--progress` flag to the git calls in `get-dependencies.sh` so people in a similar situation would have an estimate of how long initializing submodules will take.
@nglaser3 finally got around to this...
=> Add `--progress` to `get-dependencies.sh`

include/base/NekInterface.h, src/base/NekInterface.C
We usually only need heat fluxes computed on boundaries; this PR adjusts the `gradient` routine to allow calling it on a per-element basis to save on computation. This will support efficiency improvements in #1168
=> simplify gradient code

src/mesh/HexagonalSubchannelMeshBase.C, src/userobjects/HexagonalSubchannelBin.C, src/userobjects/HexagonalSubchannelGapBin.C
So we can make this parameter required in moose.
Note that this will require a moose submodule update to pass
see idaholab/moose#31215
=> Add currently optional hexagonal lattice parameter for the rotation around lattice axis
